# application.yml
spring:
  application:
    name: hhplus
  profiles:
    active: local

  # H2 Database 설정 (This is what will be used for 'local' now)
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:tcp://localhost/~/test'
    username: sa
    password:

  # H2 Console 설정
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC