CREATE TABLE USERS (
    USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(10) NOT NULL,
    USER_STATUS VARCHAR(20) NOT NULL,
    USER_POINT BIGINT NOT NULL DEFAULT 0,
    REG_DATETIME DATETIME NOT NULL
);

CREATE TABLE PRODUCT (
    PRODUCT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    PRD_STATUS VARCHAR(20) NOT NULL,
    PRODUCT_QUANTITY INT NOT NULL,
    SELL_QUANTITY INT,
    PRICE BIGINT NOT NULL,
    PRODUCT_TYPE VARCHAR(10)
);

CREATE TABLE POINT_HIST (
    POINT_HIST_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TRANSACTION_TYPE VARCHAR(20) NOT NULL,
    AMOUNT BIGINT NOT NULL,
    CURRENT_BALANCE BIGINT NOT NULL,
    TRANSACTION_DATETIME DATETIME NOT NULL,
    USER_ID BIGINT NOT NULL, -- ManyToOne 관계를 일반 컬럼으로 처리 (외래키 제약조건 없음)
    PAYMENT_ID BIGINT
);

CREATE TABLE PAYMENT (
    PAYMENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PAYMENT_STATUS VARCHAR(20) NOT NULL,
    PAYMENT_PRICE BIGINT NOT NULL,
    PAYMENT_TYPE VARCHAR(20) NOT NULL,
    PAYMENT_DATE DATETIME NOT NULL,
    ORDER_NO BIGINT
);

CREATE TABLE ORDERS (
    ORDER_NO BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_STATUS VARCHAR(20) NOT NULL,
    ORIGINAL_PRICE BIGINT NOT NULL,
    DISCOUNTED_PRICE BIGINT,
    REQUEST_QUANTITY INT,
    ORDER_DATETIME DATETIME NOT NULL,
    SOLD_DATETIME DATETIME,
    USER_ID BIGINT NOT NULL,    -- 외래 키 제약 조건 없이 일반 컬럼으로 처리
    PRODUCT_ID BIGINT NOT NULL,  -- 외래 키 제약 조건 없이 일반 컬럼으로 처리
    COUPON_ID BIGINT
);

CREATE TABLE COUPON_HIST (
    SEQ_NO BIGINT AUTO_INCREMENT PRIMARY KEY,
    COUPON_STATUS VARCHAR(20) NOT NULL,
    ISSUED_DATETIME DATETIME NOT NULL,
    USED_DATETIME DATETIME,
    COUPON_ID BIGINT NOT NULL,   -- 외래 키 제약 조건 없이 일반 컬럼으로 처리
    PRODUCT_ID BIGINT NOT NULL,  -- 외래 키 제약 조건 없이 일반 컬럼으로 처리
    USER_ID BIGINT NOT NULL      -- 외래 키 제약 조건 없이 일반 컬럼으로 처리
);

CREATE TABLE COUPON (
    COUPON_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    COUPON_NAME VARCHAR(100) NOT NULL,
    COUPON_STATUS VARCHAR(20) NOT NULL,
    COUPON_TYPE VARCHAR(2) NOT NULL,
    DISCOUNT_PERCENT INT NOT NULL,
    MAX_QUANTITY INT,
    REMAIN_QUANTITY INT,
    PRODUCT_ID BIGINT,
    VERSION BIGINT DEFAULT 0
);
